 linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - gocritic
    - unused
    - misspell
    - stylecheck
    - whitespace
    - wsl
