global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'origin-logging-elasticsearch'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9200']
